-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "deDE")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = true
L["AiFaDian"] = true
L["Click to toggle config window."] = "Klicken, um das Konfigurationsfenster umzuschalten."
L["Contributors (Github.com)"] = "Unterstützer (Github.com)"
L["Discord"] = true
L["Donate"] = "Spenden"
L["Enable"] = "Einschalten"
L["Enables / disables %s minimap icon"] = "Aktiviert / deaktiviert %s Minimapsymbol"
L["Github"] = true
L["Information"] = "Informationen"
L["KOOK"] = true
L["Ko-fi"] = true
L["Minimap icon"] = "Minikartensymbol"
L["NGA.cn"] = true
L["Put the keystone from bag automatically."] = "Lege den Schlüsselstein automatisch aus der Tasche ein."
L["QQ Group"] = "QQ Gruppe"
L["Quick Keystone"] = "Schneller Schlüsselstein"
L["Shadowmoon"] = "Schattenmond"
L["Thank you for using %s!"] = "Danke, dass du %s benutzt!"
L["Version"] = "Version"
L["Wind Chat Filter"] = "|cff5385edW|r|cff528eeci|r|cff5096ean|r|cff4e9fe8d|r |cff4ab1e4C|r|cff49b9e3h|r|cff47bfe1a|r|cff46c5e0t|r |cff42d2ddF|r|cff41d7ddi|r|cff41d7ddl|r|cff41d7ddt|r|cff41d7dde|r|cff41d7ddr|r"
L["WoW Build"] = "WoW Version"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "Du kannst deine Vorschläge oder Fehler via %s, %s, %s, %s, und in diesem Forum Thread %s posten."
