-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "esMX")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = true
L["AiFaDian"] = true
L["Click to toggle config window."] = true
L["Contributors (Github.com)"] = true
L["Discord"] = true
L["Donate"] = true
L["Enable"] = "Habilitar"
L["Enables / disables %s minimap icon"] = true
L["Github"] = true
L["Information"] = "Información"
L["KOOK"] = true
L["Ko-fi"] = true
L["Minimap icon"] = true
L["NGA.cn"] = true
L["Put the keystone from bag automatically."] = true
L["QQ Group"] = true
L["Quick Keystone"] = true
L["Shadowmoon"] = true
L["Thank you for using %s!"] = true
L["Version"] = "Versión"
L["Wind Chat Filter"] = "|cff5385edW|r|cff528eeci|r|cff5096ean|r|cff4e9fe8d|r |cff4ab1e4C|r|cff49b9e3h|r|cff47bfe1a|r|cff46c5e0t|r |cff42d2ddF|r|cff41d7ddi|r|cff41d7ddl|r|cff41d7ddt|r|cff41d7dde|r|cff41d7ddr|r"
L["WoW Build"] = true
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = true
