-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "frFR")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = true
L["AiFaDian"] = true
L["Click to toggle config window."] = true
L["Contributors (Github.com)"] = "Contributeurs (Github.com)"
L["Discord"] = "Discord"
L["Donate"] = "Faire un don"
L["Enable"] = "Activer"
L["Enables / disables %s minimap icon"] = true
L["Github"] = "Github"
L["Information"] = "Information"
L["KOOK"] = true
L["Ko-fi"] = true
L["Minimap icon"] = true
L["NGA.cn"] = "NGA.cn"
L["Put the keystone from bag automatically."] = "Mettre automatiquement la clé provenant du sac."
L["QQ Group"] = "le Groupe QQ"
L["Quick Keystone"] = "Clef rapide"
L["Shadowmoon"] = true
L["Thank you for using %s!"] = "Merci d'utiliser %s !"
L["Version"] = "Version"
L["Wind Chat Filter"] = "|cff5385edW|r|cff528eeci|r|cff5096ean|r|cff4e9fe8d|r |cff4ab1e4C|r|cff49b9e3h|r|cff47bfe1a|r|cff46c5e0t|r |cff42d2ddF|r|cff41d7ddi|r|cff41d7ddl|r|cff41d7ddt|r|cff41d7dde|r|cff41d7ddr|r"
L["WoW Build"] = "Version de WoW"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "Vous pouvez envoyer vos suggestions ou bugs via %s, %s, %s, %s et le fil de discussion dans %s."
