-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "koKR")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = true
L["Addon Message Filter"] = true
L["AiFaDian"] = true
L["Click to toggle config window."] = true
L["Contributors (Github.com)"] = "기여자(Github.com)"
L["Discord"] = true
L["Donate"] = "기부"
L["Enable"] = "사용"
L["Enable/Disable the GUID Filter Module."] = true
L["Enables / disables %s minimap icon"] = true
L["Faction Filter"] = true
L["Filter player name with default keywords."] = true
L["Filter the addon messages when you in main city."] = true
L["Filter the chat from other faction."] = true
L["Filter the chat with Padaren DK."] = true
L["Filter the message with default keywords."] = true
L["GUID Filter"] = true
L["GUID Filter Module is used to filter the chat with sender's GUID."] = true
L["Github"] = true
L["Information"] = "정보"
L["KOOK"] = true
L["Ko-fi"] = true
L["Minimap icon"] = true
L["NGA.cn"] = true
L["No Padaren DK"] = true
L["QQ Group"] = true
L["Shadowmoon"] = true
L["Simple Filters"] = true
L["Smart Massege Filter"] = true
L["Smart Name Filter"] = true
L["Some default filters for most players."] = true
L["Thank you for using %s!"] = "%s를 사용해 주셔서 감사합니다!"
L["This addon still work in progress, if you have any question or suggestion, send me via Discord."] = true
L["This filter is only for trade/lfg channel or you are in main city."] = true
L["Use Cache"] = true
L["Use cache to reduce fps drops."] = true
L["Version"] = "버전"
L["Wind Chat Filter"] = "|cff5385edW|r|cff528eeci|r|cff5096ean|r|cff4e9fe8d|r |cff4ab1e4C|r|cff49b9e3h|r|cff47bfe1a|r|cff46c5e0t|r |cff42d2ddF|r|cff41d7ddi|r|cff41d7ddl|r|cff41d7ddt|r|cff41d7dde|r|cff41d7ddr|r"
L["WoW Build"] = true
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "%s, %s, %s, %s 및 %s의 스레드를 통해 제안이나 버그 리포트를 보낼 수 있습니다."
