-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "ruRU")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = true
L["AiFaDian"] = true
L["Click to toggle config window."] = "Нажмите для перехода к окну конфигурации"
L["Contributors (Github.com)"] = "Авторы (Github.com)"
L["Discord"] = "Дискорд"
L["Donate"] = "Пожертвовать"
L["Enable"] = "Включить"
L["Enables / disables %s minimap icon"] = "Включает / отключает %s значок миникарты"
L["Github"] = true
L["Information"] = "Информация"
L["KOOK"] = true
L["Ko-fi"] = true
L["Minimap icon"] = "Значок миникарты"
L["NGA.cn"] = true
L["Put the keystone from bag automatically."] = "Выводит автоматически камень возвращения из сумки."
L["QQ Group"] = "QQ группы"
L["Quick Keystone"] = "Быстрый камень возвращения"
L["Shadowmoon"] = "Призрачная Луна"
L["Thank you for using %s!"] = "Спасибо за использование %s!"
L["Version"] = "Версия"
L["Wind Chat Filter"] = "|cff5385edW|r|cff528eeci|r|cff5096ean|r|cff4e9fe8d|r |cff4ab1e4C|r|cff49b9e3h|r|cff47bfe1a|r|cff46c5e0t|r |cff42d2ddF|r|cff41d7ddi|r|cff41d7ddl|r|cff41d7ddt|r|cff41d7dde|r|cff41d7ddr|r"
L["WoW Build"] = "Сборка WoW"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "Вы можете отправлять свои предложения или сообщения об ошибках через %s, %s, %s, %s и ветку в %s."
