-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "ruRU")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = true
L["Addon Message Filter"] = true
L["AiFaDian"] = true
L["Click to toggle config window."] = "Нажмите для перехода к окну конфигурации"
L["Contributors (Github.com)"] = "Авторы (Github.com)"
L["Discord"] = "Дискорд"
L["Donate"] = "Пожертвовать"
L["Enable"] = "Включить"
L["Enable/Disable the GUID Filter Module."] = true
L["Enables / disables %s minimap icon"] = "Включает / отключает %s значок миникарты"
L["Faction Filter"] = true
L["Filter player name with default keywords."] = true
L["Filter the addon messages when you in main city."] = true
L["Filter the chat from other faction."] = true
L["Filter the chat with Padaren DK."] = true
L["Filter the message with default keywords."] = true
L["GUID Filter"] = true
L["GUID Filter Module is used to filter the chat with sender's GUID."] = true
L["Github"] = true
L["Information"] = "Информация"
L["KOOK"] = true
L["Ko-fi"] = true
L["Minimap icon"] = "Значок миникарты"
L["NGA.cn"] = true
L["No Padaren DK"] = true
L["QQ Group"] = "QQ группы"
L["Shadowmoon"] = "Призрачная Луна"
L["Simple Filters"] = true
L["Smart Massege Filter"] = true
L["Smart Name Filter"] = true
L["Some default filters for most players."] = true
L["Thank you for using %s!"] = "Спасибо за использование %s!"
L["This addon still work in progress, if you have any question or suggestion, send me via Discord."] = true
L["This filter is only for trade/lfg channel or you are in main city."] = true
L["Use Cache"] = true
L["Use cache to reduce fps drops."] = true
L["Version"] = "Версия"
L["Wind Chat Filter"] = "|cff5385edW|r|cff528eeci|r|cff5096ean|r|cff4e9fe8d|r |cff4ab1e4C|r|cff49b9e3h|r|cff47bfe1a|r|cff46c5e0t|r |cff42d2ddF|r|cff41d7ddi|r|cff41d7ddl|r|cff41d7ddt|r|cff41d7dde|r|cff41d7ddr|r"
L["WoW Build"] = "Сборка WoW"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "Вы можете отправлять свои предложения или сообщения об ошибках через %s, %s, %s, %s и ветку в %s."
