-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "zhCN")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = "%s 是一个用于过滤游戏中一些聊天信息的插件."
L["AiFaDian"] = "爱发电"
L["Click to toggle config window."] = "点击开启设置窗口."
L["Contributors (Github.com)"] = "代码贡献者 (Github.com)"
L["Discord"] = "Discord"
L["Donate"] = "捐助"
L["Enable"] = "启用"
L["Enables / disables %s minimap icon"] = "启用/停用 %s小地图图标"
L["Github"] = true
L["Information"] = "信息"
L["KOOK"] = "KOOK (开黑啦)"
L["Ko-fi"] = "Ko-fi 美元"
L["Minimap icon"] = "小地图图标"
L["NGA.cn"] = "NGA 玩家社区"
L["Put the keystone from bag automatically."] = "自动放置背包内的传奇地下城钥石."
L["QQ Group"] = "QQ 群"
L["Quick Keystone"] = "快速钥石"
L["Shadowmoon"] = "暗影之月"
L["Thank you for using %s!"] = "感谢你使用 %s!"
L["Version"] = "版本"
L["Wind Chat Filter"] = "|cff5385edW|r|cff5093eai|r|cff4ea1e8n|r|cff4bb0e5d|r |cff46c5e0聊|r|cff43d0de天|r|cff41d7dd过|r|cff41d7dd滤|r|cff41d7dd器|r"
L["WoW Build"] = "魔兽世界版本号"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "你可以通过 %s, %s, %s, %s 和在 %s 的帖子来发送你的建议和错误."
