-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "zhTW")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = "%s 是一個用於過濾遊戲中一些聊天信息的插件."
L["AiFaDian"] = "愛發電"
L["Click to toggle config window."] = "點擊開啟設定窗口."
L["Contributors (Github.com)"] = "代碼貢獻者 (Github.com)"
L["Discord"] = true
L["Donate"] = "捐助"
L["Enable"] = "開啟"
L["Enables / disables %s minimap icon"] = "開啟/關閉 %s小地圖圖標"
L["Github"] = true
L["Information"] = "信息"
L["KOOK"] = true
L["Ko-fi"] = "Ko-fi 美元"
L["Minimap icon"] = "小地圖圖標"
L["NGA.cn"] = "NGA 玩家社區"
L["Put the keystone from bag automatically."] = "自動放置背包中的傳奇地城鑰石."
L["QQ Group"] = "QQ 群"
L["Quick Keystone"] = "快速鑰石"
L["Shadowmoon"] = "暗影之月"
L["Thank you for using %s!"] = "感謝你使用 %s!"
L["Version"] = "版本"
L["Wind Chat Filter"] = "|cff5385edW|r|cff5093eai|r|cff4ea1e8n|r|cff4bb0e5d|r |cff46c5e0聊|r|cff43d0de天|r|cff41d7dd過|r|cff41d7dd濾|r|cff41d7dd器|r"
L["WoW Build"] = "魔獸世界版本號"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "你可以透過 %s, %s, %s, %s 和在 %s 的帖子來回報錯誤和建議."
