-- Generated by WindToolsScripts
-- https://github.com/fang2hou/WindToolsScripts
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "zhTW")
if not L then return end

L["%s is an addon aimed to filter some chat messages in game."] = "%s 是一個用於過濾遊戲中一些聊天訊息的插件."
L["Addon Message Filter"] = "插件訊息過濾"
L["AiFaDian"] = "愛發電"
L["Click to toggle config window."] = "點擊開啟設定視窗."
L["Contributors (Github.com)"] = "代碼貢獻者 (Github.com)"
L["Discord"] = true
L["Donate"] = "捐助"
L["Enable"] = "開啟"
L["Enable/Disable the GUID Filter Module."] = "開啟/關閉 GUID 過濾模組."
L["Enables / disables %s minimap icon"] = "開啟/關閉 %s小地圖圖示"
L["Faction Filter"] = "陣營過濾"
L["Filter player name with default keywords."] = "使用預設的關鍵字過濾玩家名稱."
L["Filter the addon messages when you in main city."] = "在主城時過濾插件訊息."
L["Filter the chat from other faction."] = "過濾來自其他陣營的聊天訊息."
L["Filter the chat with Padaren DK."] = "過濾來自熊貓人死亡騎士的聊天訊息."
L["Filter the message with default keywords."] = "使用預設的關鍵字過濾聊天訊息."
L["GUID Filter"] = "GUID 過濾"
L["GUID Filter Module is used to filter the chat with sender's GUID."] = "GUID 過濾模組用於過濾來自特定 GUID 的聊天訊息."
L["Github"] = true
L["Information"] = "訊息"
L["KOOK"] = true
L["Ko-fi"] = "Ko-fi 美元"
L["Minimap icon"] = "小地圖圖示"
L["NGA.cn"] = "NGA 玩家社區"
L["No Padaren DK"] = "過濾熊貓人死亡騎士"
L["QQ Group"] = "QQ 群"
L["Shadowmoon"] = "暗影之月"
L["Simple Filters"] = "簡單過濾器"
L["Smart Massege Filter"] = "智能訊息過濾"
L["Smart Name Filter"] = "智能角色名過濾"
L["Some default filters for most players."] = "為大多數玩家提供的一些預設過濾器."
L["Thank you for using %s!"] = "感謝你使用 %s!"
L["This addon still work in progress, if you have any question or suggestion, send me via Discord."] = "這個插件仍在開發中, 如果你有任何問題或建議, 請通過 Discord 聯繫我."
L["This filter is only for trade/lfg channel or you are in main city."] = "這個過濾器僅適用於交易/尋求組隊頻道或者當你在主城時."
L["Use Cache"] = "使用快取"
L["Use cache to reduce fps drops."] = "使用快取來減少 FPS 影響."
L["Version"] = "版本"
L["Wind Chat Filter"] = "|cff5385edW|r|cff5093eai|r|cff4ea1e8n|r|cff4bb0e5d|r |cff46c5e0聊|r|cff43d0de天|r|cff41d7dd過|r|cff41d7dd濾|r|cff41d7dd器|r"
L["WoW Build"] = "魔獸世界版本號"
L["You can send your suggestions or bugs via %s, %s, %s, %s and the thread in %s."] = "你可以透過 %s, %s, %s, %s 和在 %s 的帖子來回報錯誤和建議."
